### ISSUE TITLE
incompatible with Python 3.11 (?)

### ISSUE THREAD

**Issue by a-schommer** [nottheswimmer/pytago#24]
I can' get it to work in my environment. Even starting pytago without any arg leads to:
```python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python311\Scripts\pytago.exe\__main__.py", line 4, in <module>
  File "C:\Program Files\Python311\Lib\site-packages\pytago\__init__.py", line 1, in <module>
    from pytago.core import *
  File "C:\Program Files\Python311\Lib\site-packages\pytago\core.py", line 24, in <module>
    import astroid
  File "C:\Program Files\Python311\Lib\site-packages\astroid\__init__.py", line 53, in <module>
    from astroid import inference, raw_building
  File "C:\Program Files\Python311\Lib\site-packages\astroid\inference.py", line 33, in <module>
    import wrapt
  File "C:\Program Files\Python311\Lib\site-packages\wrapt\__init__.py", line 10, in <module>
    from .decorators import (adapter_factory, AdapterFactory, decorator,
  File "C:\Program Files\Python311\Lib\site-packages\wrapt\decorators.py", line 34, in <module>
    from inspect import ismethod, isclass, formatargspec
ImportError: cannot import name 'formatargspec' from 'inspect' (C:\Program Files\Python311\Lib\inspect.py)
```
(and the program aborts; similair Traceback if you try to `import pytago`).

The python docu for 3.10.11 on `inspect.formatargspec()` notes:
```
Deprecated since version 3.5: Use signature() and Signature Object, which provide a better introspecting API for callables.
```
where the 3.11 docu on inspect does not mention `formatargspec()`.

My environment is:
- Windows 10, 64bit
- Python 3.11.3 (64bit)
- pytago 0.0.12

**Comment by endmarsfr** [comment]
Hi,

I had the same error too.
I hope that could be solved before next Python release 

Regards

**Comment by endmarsfr** [comment]
Hi

Any news ?

**Comment by endmarsfr** [comment]
Hi,
I fixed it, it's because wrapt isnt the latest version, after installing pytago just do  `python -m pip install wrapt --force-reinstall` to force latest wrapt to install
